#ifndef NATIVE_CLIENT_SRC_PUBLIC_RIPPLE_LEDGER_SERVICE_H_
#define NATIVE_CLIENT_SRC_PUBLIC_RIPPLE_LEDGER_SERVICE_H_

#define NACL_RIPPLE_LEDGER_SERVICE_READ  "read_ledger:s:C"
/* ledger hash
   -> ledger data */

#endif /* NATIVE_CLIENT_SRC_PUBLIC_RIPPLE_LEDGER_SERVICE_H_ */
